version: 2.1

orbs:
  maven: circleci/maven@1.0.3

workflows:
  maven_test:
    jobs:
      - maven/test:
          command: 'integration-test cobertura:cobertura'
    commands:
      - with_cache:
          steps: bash <(curl -s https://codecov.io/bash)
